from database import SessionLocal
from models import Question

db = SessionLocal()

# همه سوالات موجود رو بگیر (فقط متن‌هاشون)
existing_texts = {q.text for q in db.query(Question).all()}
print(f"Existing questions: {len(existing_texts)}")

questions = [
    # ==================== PYTHON BASICS ====================
    {
        "text": "خروجی print(type(5)) چی هست؟",
        "option_a": "<class 'int'>",
        "option_b": "<class 'str'>",
        "option_c": "<class 'float'>",
        "option_d": "خطا می‌ده",
        "correct_option": "a",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "برای تعریف یه تابع تو پایتون از چه کلمه‌ای استفاده می‌کنیم؟",
        "option_a": "function",
        "option_b": "def",
        "option_c": "fun",
        "option_d": "define",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کدوم یکی از اینا لیست تو پایتونه؟",
        "option_a": "(1, 2, 3)",
        "option_b": "{1, 2, 3}",
        "option_c": "[1, 2, 3]",
        "option_d": "<1, 2, 3>",
        "correct_option": "c",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی 2 ** 3 تو پایتون چیه؟",
        "option_a": "6",
        "option_b": "8",
        "option_c": "9",
        "option_d": "23",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی len('hello') چیه؟",
        "option_a": "4",
        "option_b": "5",
        "option_c": "6",
        "option_d": "خطا می‌ده",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کدوم یکی از اینا tuple هست؟",
        "option_a": "[1, 2, 3]",
        "option_b": "(1, 2, 3)",
        "option_c": "{1, 2, 3}",
        "option_d": "<1, 2, 3>",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کدوم متد به آخر لیست اضافه می‌کنه؟",
        "option_a": "add()",
        "option_b": "push()",
        "option_c": "append()",
        "option_d": "insert()",
        "correct_option": "c",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی 10 // 3 تو پایتون چیه؟",
        "option_a": "3",
        "option_b": "3.33",
        "option_c": "4",
        "option_d": "1",
        "correct_option": "a",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی 10 % 3 تو پایتون چیه؟",
        "option_a": "0",
        "option_b": "1",
        "option_c": "3",
        "option_d": "3.33",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی 'abc'[1] چیه؟",
        "option_a": "a",
        "option_b": "b",
        "option_c": "c",
        "option_d": "خطا",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کدوم یکی از اینا set تو پایتونه؟",
        "option_a": "[1, 2, 3]",
        "option_b": "(1, 2, 3)",
        "option_c": "{1, 2, 3}",
        "option_d": "<1, 2, 3>",
        "correct_option": "c",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "برای کامنت تو پایتون از چی استفاده می‌کنیم؟",
        "option_a": "//",
        "option_b": "/*",
        "option_c": "#",
        "option_d": "--",
        "correct_option": "c",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "چطور رشته '5' رو به عدد صحیح تبدیل کنیم؟",
        "option_a": "str('5')",
        "option_b": "int('5')",
        "option_c": "float('5')",
        "option_d": "num('5')",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کدوم اسم متغیر تو پایتون نامعتبره؟",
        "option_a": "_name",
        "option_b": "myVar",
        "option_c": "2var",
        "option_d": "name2",
        "correct_option": "c",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی bool([]) چیه؟",
        "option_a": "True",
        "option_b": "False",
        "option_c": "None",
        "option_d": "خطا",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "کدوم یکی از اینا غیرقابل‌تغییر (immutable) هست؟",
        "option_a": "list",
        "option_b": "dict",
        "option_c": "set",
        "option_d": "tuple",
        "correct_option": "d",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "برای تعریف کلاس از چه کلمه‌ای استفاده می‌کنیم؟",
        "option_a": "class",
        "option_b": "object",
        "option_c": "def",
        "option_d": "struct",
        "correct_option": "a",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی sorted([3, 1, 2]) چیه؟",
        "option_a": "[3, 2, 1]",
        "option_b": "[1, 2, 3]",
        "option_c": "[1, 3, 2]",
        "option_d": "خطا",
        "correct_option": "b",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "تابع input() چه نوعی برمی‌گردونه؟",
        "option_a": "int",
        "option_b": "float",
        "option_c": "str",
        "option_d": "bool",
        "correct_option": "c",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "خروجی list(range(3)) چیه؟",
        "option_a": "[1, 2, 3]",
        "option_b": "[0, 1, 2]",
        "option_c": "[0, 1, 2, 3]",
        "option_d": "[3]",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "خروجی 'Hello' + ' ' + 'World' چیه؟",
        "option_a": "Hello World",
        "option_b": "HelloWorld",
        "option_c": "Hello+World",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "چطور چک کنیم یه کلید تو دیکشنری وجود داره؟",
        "option_a": "key.exists(dict)",
        "option_b": "key in dict",
        "option_c": "dict.has(key)",
        "option_d": "dict.contains(key)",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "برای حذف یه کلید از دیکشنری از کدوم متد استفاده می‌کنیم؟",
        "option_a": "delete()",
        "option_b": "remove()",
        "option_c": "pop()",
        "option_d": "discard()",
        "correct_option": "c",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "خروجی [1, 2, 3, 4][1:3] چیه؟",
        "option_a": "[1, 2]",
        "option_b": "[2, 3]",
        "option_c": "[3, 4]",
        "option_d": "[2, 3, 4]",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "خروجی print(type(None)) چیه؟",
        "option_a": "<class 'NoneType'>",
        "option_b": "<class 'null'>",
        "option_c": "<class 'void'>",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "کدوم یکی از اینا list comprehension هست؟",
        "option_a": "[x*2 for x in range(5)]",
        "option_b": "for x in range(5): x*2",
        "option_c": "list(x*2, range(5))",
        "option_d": "map(x*2, range(5))",
        "correct_option": "a",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "خروجی list(filter(lambda x: x > 2, [1, 2, 3, 4])) چیه؟",
        "option_a": "[1, 2]",
        "option_b": "[3, 4]",
        "option_c": "[2, 3]",
        "option_d": "[1, 2, 3, 4]",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "کاربرد *args تو پایتون چیه؟",
        "option_a": "گرفتن تعداد متغیر آرگومان مکانی",
        "option_b": "گرفتن تعداد متغیر آرگومان کلیدواژه‌ای",
        "option_c": "ضرب آرگومان‌ها",
        "option_d": "اشاره‌گر",
        "correct_option": "a",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "کاربرد **kwargs چیه؟",
        "option_a": "گرفتن آرگومان‌های مکانی",
        "option_b": "گرفتن آرگومان‌های کلیدواژه‌ای",
        "option_c": "توان رسانی",
        "option_d": "خطا",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "یه generator تو پایتون از کدوم کلمه کلیدی استفاده می‌کنه؟",
        "option_a": "return",
        "option_b": "yield",
        "option_c": "generate",
        "option_d": "async",
        "correct_option": "b",
        "category": "python", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "کاربرد finally تو try/except چیه؟",
        "option_a": "همیشه اجرا میشه، حتی با خطا",
        "option_b": "فقط وقتی خطا باشه",
        "option_c": "فقط وقتی خطا نباشه",
        "option_d": "هیچ‌وقت اجرا نمیشه",
        "correct_option": "a",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "خروجی f'{5:03d}' چیه؟",
        "option_a": "'5'",
        "option_b": "'05'",
        "option_c": "'005'",
        "option_d": "'0005'",
        "correct_option": "c",
        "category": "python", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "تفاوت is و == تو پایتون چیه؟",
        "option_a": "هیچ فرقی ندارن",
        "option_b": "is هویت رو چک می‌کنه، == برابری مقدار",
        "option_c": "== هویت رو چک می‌کنه، is برابری مقدار",
        "option_d": "is فقط برای اعداد",
        "correct_option": "b",
        "category": "python", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "متد __init__ تو کلاس پایتون چیکار می‌کنه؟",
        "option_a": "کلاس رو حذف می‌کنه",
        "option_b": "سازنده کلاسه (constructor)",
        "option_c": "کلاس رو کپی می‌کنه",
        "option_d": "خطا می‌ده",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "تابع enumerate چیکار می‌کنه؟",
        "option_a": "یه لیست جدید می‌سازه",
        "option_b": "زوج (index, value) برمی‌گردونه",
        "option_c": "اعداد رو جمع می‌کنه",
        "option_d": "لیست رو مرتب می‌کنه",
        "correct_option": "b",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "تابع zip چیکار می‌کنه؟",
        "option_a": "دو تا لیست رو به هم می‌چسبونه",
        "option_b": "فایل zip می‌سازه",
        "option_c": "دو لیست رو جفت می‌کنه",
        "option_d": "لیست رو پاک می‌کنه",
        "correct_option": "c",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "تابع map چیکار می‌کنه؟",
        "option_a": "یه تابع رو روی همه اعضای iterable اعمال می‌کنه",
        "option_b": "یه دیکشنری می‌سازه",
        "option_c": "فیلتر می‌کنه",
        "option_d": "لیست رو مرتب می‌کنه",
        "correct_option": "a",
        "category": "python", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "خروجی print(1 == 1.0) چیه؟",
        "option_a": "True",
        "option_b": "False",
        "option_c": "خطا",
        "option_d": "None",
        "correct_option": "a",
        "category": "python", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "برای تعریف رشته چند خطی از چی استفاده می‌کنیم؟",
        "option_a": "'text'",
        "option_b": "\"text\"",
        "option_c": "'''text'''",
        "option_d": "//text//",
        "correct_option": "c",
        "category": "python", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی list(zip([1,2],['a','b'])) چیه؟",
        "option_a": "[(1,'a'), (2,'b')]",
        "option_b": "[1, 'a', 2, 'b']",
        "option_c": "[[1,'a'], [2,'b']]",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "python", "difficulty": "hard", "xp_reward": 25,
    },

    # ==================== JAVASCRIPT ====================
    {
        "text": "تو جاوااسکریپت، برای متغیر غیرقابل‌تغییر از چی استفاده می‌کنیم؟",
        "option_a": "var",
        "option_b": "let",
        "option_c": "const",
        "option_d": "def",
        "correct_option": "c",
        "category": "javascript", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "خروجی typeof [] تو جاوااسکریپت چیه؟",
        "option_a": "'array'",
        "option_b": "'list'",
        "option_c": "'object'",
        "option_d": "'undefined'",
        "correct_option": "c",
        "category": "javascript", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "خروجی typeof null چیه؟",
        "option_a": "'null'",
        "option_b": "'object'",
        "option_c": "'undefined'",
        "option_d": "'void'",
        "correct_option": "b",
        "category": "javascript", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "خروجی '5' + 3 تو جاوااسکریپت چیه؟",
        "option_a": "8",
        "option_b": "'53'",
        "option_c": "خطا",
        "option_d": "'8'",
        "correct_option": "b",
        "category": "javascript", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "خروجی '5' - 3 تو جاوااسکریپت چیه؟",
        "option_a": "2",
        "option_b": "'53'",
        "option_c": "NaN",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "javascript", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "تفاوت == و === تو جاوااسکریپت چیه؟",
        "option_a": "=== نوع رو هم چک می‌کنه",
        "option_b": "== سریع‌تره",
        "option_c": "=== فقط برای اعداد",
        "option_d": "هیچ فرقی ندارن",
        "correct_option": "a",
        "category": "javascript", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "کدوم متد به آخر آرایه اضافه می‌کنه؟",
        "option_a": "append()",
        "option_b": "push()",
        "option_c": "add()",
        "option_d": "insert()",
        "correct_option": "b",
        "category": "javascript", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کدوم متد آخرین عضو آرایه رو حذف می‌کنه؟",
        "option_a": "shift()",
        "option_b": "remove()",
        "option_c": "pop()",
        "option_d": "delete()",
        "correct_option": "c",
        "category": "javascript", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "متد map روی آرایه چیکار می‌کنه؟",
        "option_a": "فیلتر می‌کنه",
        "option_b": "یه آرایه جدید با نتایج برمی‌گردونه",
        "option_c": "جمع می‌کنه",
        "option_d": "مرتب می‌کنه",
        "correct_option": "b",
        "category": "javascript", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "متد filter روی آرایه چیکار می‌کنه؟",
        "option_a": "آرایه رو به یه مقدار تبدیل می‌کنه",
        "option_b": "آرایه جدید با اعضای موردنظر برمی‌گردونه",
        "option_c": "آرایه رو مرتب می‌کنه",
        "option_d": "حذف می‌کنه",
        "correct_option": "b",
        "category": "javascript", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "متد reduce چیکار می‌کنه؟",
        "option_a": "آرایه رو به یه مقدار واحد تبدیل می‌کنه",
        "option_b": "فیلتر می‌کنه",
        "option_c": "کپی می‌کنه",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "javascript", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "Promise تو جاوااسکریپت چیه؟",
        "option_a": "یه نوع داده ساده",
        "option_b": "یه شیء برای عملیات غیرهمزمان",
        "option_c": "یه حلقه",
        "option_d": "یه آرایه",
        "correct_option": "b",
        "category": "javascript", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "async/await برای چیه؟",
        "option_a": "ساده‌تر کردن کار با Promise‌ها",
        "option_b": "سریع‌تر کردن کد",
        "option_c": "تعریف متغیر",
        "option_d": "حلقه زدن",
        "correct_option": "a",
        "category": "javascript", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "سینتکس arrow function چیه؟",
        "option_a": "function() {}",
        "option_b": "() => {}",
        "option_c": "() -> {}",
        "option_d": "def() {}",
        "correct_option": "b",
        "category": "javascript", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "JSON.parse چیکار می‌کنه؟",
        "option_a": "شیء رو به رشته تبدیل می‌کنه",
        "option_b": "رشته JSON رو به شیء تبدیل می‌کنه",
        "option_c": "فایل می‌خونه",
        "option_d": "خطا",
        "correct_option": "b",
        "category": "javascript", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "JSON.stringify چیکار می‌کنه؟",
        "option_a": "شیء رو به رشته JSON تبدیل می‌کنه",
        "option_b": "رشته رو به شیء تبدیل می‌کنه",
        "option_c": "کپی می‌کنه",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "javascript", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "تفاوت let و var چیه؟",
        "option_a": "let محدود به بلاک، var تابعی",
        "option_b": "هیچ فرقی ندارن",
        "option_c": "var جدیدتره",
        "option_d": "let فقط تو حلقه",
        "correct_option": "a",
        "category": "javascript", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "کدوم یکی از اینا falsy تو جاوااسکریپت نیست؟",
        "option_a": "0",
        "option_b": "''",
        "option_c": "'0'",
        "option_d": "null",
        "correct_option": "c",
        "category": "javascript", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "Spread operator تو جاوااسکریپت چیه؟",
        "option_a": "...",
        "option_b": "***",
        "option_c": "---",
        "option_d": ">>>",
        "correct_option": "a",
        "category": "javascript", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "setTimeout چیکار می‌کنه؟",
        "option_a": "بعد از یه مدت زمان، تابع رو اجرا می‌کنه",
        "option_b": "فوراً اجرا می‌کنه",
        "option_c": "حلقه می‌زنه",
        "option_d": "متوقف می‌کنه",
        "correct_option": "a",
        "category": "javascript", "difficulty": "medium", "xp_reward": 15,
    },

    # ==================== ALGORITHMS ====================
    {
        "text": "پیچیدگی زمانی binary search چیه؟",
        "option_a": "O(n)",
        "option_b": "O(log n)",
        "option_c": "O(n²)",
        "option_d": "O(1)",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "پیچیدگی زمانی linear search چیه؟",
        "option_a": "O(1)",
        "option_b": "O(log n)",
        "option_c": "O(n)",
        "option_d": "O(n²)",
        "correct_option": "c",
        "category": "algorithm", "difficulty": "easy", "xp_reward": 15,
    },
    {
        "text": "پیچیدگی زمانی bubble sort چیه؟",
        "option_a": "O(n)",
        "option_b": "O(n log n)",
        "option_c": "O(n²)",
        "option_d": "O(log n)",
        "correct_option": "c",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "پیچیدگی متوسط quicksort چیه؟",
        "option_a": "O(n)",
        "option_b": "O(n log n)",
        "option_c": "O(n²)",
        "option_d": "O(log n)",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "ساختار داده Stack چطور کار می‌کنه؟",
        "option_a": "اولین ورودی، اولین خروجی (FIFO)",
        "option_b": "آخرین ورودی، اولین خروجی (LIFO)",
        "option_c": "تصادفی",
        "option_d": "مرتب",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "easy", "xp_reward": 15,
    },
    {
        "text": "ساختار داده Queue چطور کار می‌کنه؟",
        "option_a": "LIFO",
        "option_b": "FIFO",
        "option_c": "تصادفی",
        "option_d": "مرتب",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "easy", "xp_reward": 15,
    },
    {
        "text": "Recursion چیه؟",
        "option_a": "تابعی که خودش رو صدا می‌زنه",
        "option_b": "حلقه بی‌نهایت",
        "option_c": "یه نوع آرایه",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "algorithm", "difficulty": "easy", "xp_reward": 15,
    },
    {
        "text": "DFS مخفف چیه؟",
        "option_a": "Data File System",
        "option_b": "Depth First Search",
        "option_c": "Direct File Search",
        "option_d": "Digital First System",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "BFS مخفف چیه؟",
        "option_a": "Breadth First Search",
        "option_b": "Binary File System",
        "option_c": "Big File Search",
        "option_d": "Basic First Search",
        "correct_option": "a",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "پیچیدگی دسترسی به یه عضو آرایه با ایندکس چیه؟",
        "option_a": "O(n)",
        "option_b": "O(log n)",
        "option_c": "O(1)",
        "option_d": "O(n²)",
        "correct_option": "c",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "پیچیدگی جستجو تو hash table (میانگین) چیه؟",
        "option_a": "O(1)",
        "option_b": "O(log n)",
        "option_c": "O(n)",
        "option_d": "O(n²)",
        "correct_option": "a",
        "category": "algorithm", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "تو linked list، چطور به عضو بعدی دسترسی داریم؟",
        "option_a": "با ایندکس",
        "option_b": "با pointer به عضو بعدی",
        "option_c": "با کلید",
        "option_d": "تصادفی",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "تو یه binary tree، هر گره حداکثر چند فرزند داره؟",
        "option_a": "1",
        "option_b": "2",
        "option_c": "3",
        "option_d": "بی‌نهایت",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "easy", "xp_reward": 15,
    },
    {
        "text": "Memoization چیه؟",
        "option_a": "ذخیره نتایج محاسبات برای استفاده دوباره",
        "option_b": "پاک کردن حافظه",
        "option_c": "یه نوع آرایه",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "algorithm", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "Dynamic Programming چیه؟",
        "option_a": "برنامه‌نویسی پویا با حل زیرمسائل",
        "option_b": "یه زبان برنامه‌نویسی",
        "option_c": "یه فریم‌ورک",
        "option_d": "یه دیتابیس",
        "correct_option": "a",
        "category": "algorithm", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "Base case تو recursion چیه؟",
        "option_a": "شرط توقف بازگشت",
        "option_b": "شروع بازگشت",
        "option_c": "حلقه",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "بهترین ساختار داده برای undo چیه؟",
        "option_a": "Queue",
        "option_b": "Stack",
        "option_c": "Array",
        "option_d": "Tree",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "فیبوناچی بازگشتی بدون memoization چه پیچیدگی داره؟",
        "option_a": "O(n)",
        "option_b": "O(log n)",
        "option_c": "O(2^n)",
        "option_d": "O(n²)",
        "correct_option": "c",
        "category": "algorithm", "difficulty": "hard", "xp_reward": 30,
    },
    {
        "text": "بدترین حالت quicksort چیه؟",
        "option_a": "O(n)",
        "option_b": "O(n log n)",
        "option_c": "O(n²)",
        "option_d": "O(log n)",
        "correct_option": "c",
        "category": "algorithm", "difficulty": "hard", "xp_reward": 25,
    },
    {
        "text": "کدوم مرتب‌سازی پایدار (stable) هست؟",
        "option_a": "quicksort",
        "option_b": "merge sort",
        "option_c": "heap sort",
        "option_d": "selection sort",
        "correct_option": "b",
        "category": "algorithm", "difficulty": "hard", "xp_reward": 30,
    },

    # ==================== GENERAL PROGRAMMING ====================
    {
        "text": "Git چیه؟",
        "option_a": "یه زبان برنامه‌نویسی",
        "option_b": "یه سیستم کنترل نسخه",
        "option_c": "یه دیتابیس",
        "option_d": "یه ویرایشگر متن",
        "correct_option": "b",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "دستور git commit چیکار می‌کنه؟",
        "option_a": "تغییرات رو ذخیره می‌کنه",
        "option_b": "فایل جدید می‌سازه",
        "option_c": "پروژه رو پاک می‌کنه",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "Pull Request چیه؟",
        "option_a": "درخواست کشیدن تغییرات",
        "option_b": "درخواست ادغام تغییرات تو یه ریپو",
        "option_c": "حذف ریپو",
        "option_d": "ساخت ریپو",
        "correct_option": "b",
        "category": "general", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "HTTP مخفف چیه؟",
        "option_a": "HyperText Transfer Protocol",
        "option_b": "High Tech Transfer Program",
        "option_c": "Home Tool Terminal Protocol",
        "option_d": "HyperText Test Program",
        "correct_option": "a",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کد وضعیت HTTP 404 چی رو نشون می‌ده؟",
        "option_a": "خطای سرور",
        "option_b": "پیدا نشد",
        "option_c": "موفق",
        "option_d": "ریدایرکت",
        "correct_option": "b",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "کد وضعیت HTTP 500 چی رو نشون می‌ده؟",
        "option_a": "خطای سرور",
        "option_b": "خطای کاربر",
        "option_c": "موفق",
        "option_d": "ریدایرکت",
        "correct_option": "a",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "JSON چیه؟",
        "option_a": "یه زبان برنامه‌نویسی",
        "option_b": "یه فرمت تبادل داده",
        "option_c": "یه دیتابیس",
        "option_d": "یه فریم‌ورک",
        "correct_option": "b",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "API چیه؟",
        "option_a": "رابط برنامه‌نویسی کاربردی",
        "option_b": "یه زبان",
        "option_c": "یه دیتابیس",
        "option_d": "یه سیستم‌عامل",
        "correct_option": "a",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "SQL چیه؟",
        "option_a": "یه زبان برنامه‌نویسی عمومی",
        "option_b": "زبان پرس‌وجوی دیتابیس",
        "option_c": "یه فرمت عکس",
        "option_d": "یه سیستم‌عامل",
        "correct_option": "b",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
    {
        "text": "Primary Key تو دیتابیس چیه؟",
        "option_a": "کلید اصلی که هر رکورد رو یکتا می‌کنه",
        "option_b": "کلید خارجی",
        "option_c": "رمز عبور",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "general", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "Foreign Key چیه؟",
        "option_a": "کلید اصلی",
        "option_b": "کلیدی که به جدول دیگه اشاره می‌کنه",
        "option_c": "رمز",
        "option_d": "خطا",
        "correct_option": "b",
        "category": "general", "difficulty": "medium", "xp_reward": 15,
    },
    {
        "text": "REST چیه؟",
        "option_a": "یه سبک معماری برای API",
        "option_b": "یه زبان",
        "option_c": "یه دیتابیس",
        "option_d": "یه فریم‌ورک",
        "correct_option": "a",
        "category": "general", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "Docker چیه؟",
        "option_a": "یه ابزار برای بسته‌بندی و اجرای اپلیکیشن تو محیط مجزا",
        "option_b": "یه زبان",
        "option_c": "یه دیتابیس",
        "option_d": "یه ویرایشگر",
        "correct_option": "a",
        "category": "general", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "ORM چیه؟",
        "option_a": "نقشه‌برداری شیء-رابطه‌ای برای کار با دیتابیس",
        "option_b": "یه زبان",
        "option_c": "یه سیستم‌عامل",
        "option_d": "یه فرمت فایل",
        "correct_option": "a",
        "category": "general", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "CI/CD چیه؟",
        "option_a": "یکپارچه‌سازی و استقرار مداوم",
        "option_b": "یه دیتابیس",
        "option_c": "یه زبان",
        "option_d": "یه IDE",
        "correct_option": "a",
        "category": "general", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "Unit Test چیه؟",
        "option_a": "تست یه بخش کوچیک از کد",
        "option_b": "تست کل سیستم",
        "option_c": "تست دستی",
        "option_d": "تست شبکه",
        "correct_option": "a",
        "category": "general", "difficulty": "easy", "xp_reward": 15,
    },
    {
        "text": "MVC مخفف چیه؟",
        "option_a": "Model View Controller",
        "option_b": "Multi Version Control",
        "option_c": "Machine Virtual Code",
        "option_d": "Main Variable Container",
        "correct_option": "a",
        "category": "general", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "Design Pattern چیه؟",
        "option_a": "راه‌حل‌های تکرارشونده برای مشکلات رایج طراحی",
        "option_b": "یه فرمت عکس",
        "option_c": "یه زبان",
        "option_d": "یه دیتابیس",
        "correct_option": "a",
        "category": "general", "difficulty": "medium", "xp_reward": 20,
    },
    {
        "text": "Refactoring چیه؟",
        "option_a": "بهبود ساختار کد بدون تغییر رفتار",
        "option_b": "حذف کد",
        "option_c": "نوشتن از صفر",
        "option_d": "خطا",
        "correct_option": "a",
        "category": "general", "difficulty": "easy", "xp_reward": 15,
    },
    {
        "text": "Version Control چیه؟",
        "option_a": "سیستم مدیریت تغییرات کد در طول زمان",
        "option_b": "یه زبان",
        "option_c": "یه دیتابیس",
        "option_d": "یه IDE",
        "correct_option": "a",
        "category": "general", "difficulty": "easy", "xp_reward": 10,
    },
]

added = 0
skipped = 0

for q in questions:
    if q["text"] in existing_texts:
        skipped += 1
        continue
    db.add(Question(**q))
    added += 1

db.commit()
db.close()

print(f"Added: {added}")
print(f"Skipped (already exists): {skipped}")
print(f"Total questions now in DB: {len(existing_texts) + added}")